name: 'run'

on:
  schedule:
    - cron: '30 16 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: 'setup python'
       uses: actions/setup-python@master
       with: 
         python-version: 3.7
       
     - name: main
       env:
         SCKEY: ${{ secrets.SCKEY }}
         username: ${{ secrets.username }}
         password: ${{ secrets.password }}
         fflogin_name: ${{ secrets.fflogin_name }}
         fflogin_password: ${{ secrets.fflogin_password }}
         area_name: ${{ secrets.area_name }}
         server_name: ${{ secrets.server_name }}
         role_name: ${{ secrets.role_name }}
         cookie_52pj: ${{ secrets.cookie_52pj }}
         cookie_smzdm: ${{ secrets.cookie_smzdm }}
         netease_username: ${{ secrets.netease_username }}
         netease_password: ${{ secrets.netease_password }}
       run: |
         pip3 install -r requirements.txt
         python3 ./Cloud189Checkin/C189CheckinForSCF.py
         python3 ./FF14Checkin/FF14CheckinForSCF.py
         python3 ./Checkin52pj/Checkin52pjForSCF.py
         python3 ./smzdmCheckin/smzdmCheckinForSCF.py
         python3 ./NetEase_Music_daily/NetEase_Music_dailyForSCF.py
